alter table MYCABINET_RESPONSE_ATTACHMENT_LINK add constraint FK_RESATT_RESPONSE foreign key (RESPONSE_ID) references MYCABINET_RESPONSE(ID);
alter table MYCABINET_RESPONSE_ATTACHMENT_LINK add constraint FK_RESATT_ATTACHMENT foreign key (ATTACHMENT_ID) references MYCABINET_ATTACHMENT(ID);
